### ISSUE TITLE
Не работает после обновления HA 2023.06

### ISSUE THREAD

**Issue by booroondook-eng** [AlexxIT/MorphNumbers#24]
В разделе интеграций пометка "Не загружено"
![2023-06-08 21_07_44-Window](https://github.com/AlexxIT/MorphNumbers/assets/8210458/c13b7421-8579-4f90-a830-2563a6f6c7e5)
Перезагрузка интеграции не помогает.

**Comment by dreem2001** [comment]
Добавлю лог

```Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:577
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:23:46 PM (1 occurrences)
Last logged: 11:23:46 PM

[281472675419024] The system cannot restart because the configuration is not valid: Component error: morph_numbers - Exception importing custom_components.morph_numbers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 577, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: morph_numbers - Exception importing custom_components.morph_numbers
```

**Comment by jayzee021** [comment]
Эта ошибка возникла в пользовательской интеграции.

Logger: homeassistant.loader
Source: custom_components/morph_numbers/utils.py:47
Integration: morph_numbers (documentation, issues)
First occurred: 10:38:01 (1 occurrences)
Last logged: 10:38:01

Unexpected exception importing component custom_components.morph_numbers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/morph_numbers/__init__.py", line 10, in <module>
    MORPH = MorphNumber()
            ^^^^^^^^^^^^^
  File "/config/custom_components/morph_numbers/utils.py", line 47, in __init__
    morph = MorphAnalyzer()
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymorphy2/analyzer.py", line 224, in __init__
    self._init_units(units)
  File "/usr/local/lib/python3.11/site-packages/pymorphy2/analyzer.py", line 235, in _init_units
    self._units.append((self._bound_unit(unit), False))
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymorphy2/analyzer.py", line 246, in _bound_unit
    unit = unit.clone()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymorphy2/units/base.py", line 35, in clone
    return self.__class__(**self._get_params())
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymorphy2/units/base.py", line 76, in _get_params
    (key, getattr(self, key, None)) for key in self._get_param_names()
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymorphy2/units/base.py", line 70, in _get_param_names
    args, varargs, kw, default = inspect.getargspec(cls.__init__)
                                 ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'

**Comment by stduba** [comment]
Не работает после обновления HA 2023.06. Невозможно удалить интеграцию. При попытке удалить ничего не происходит.

**Comment by slakouz** [comment]
Подтверждаю, перестал работать после обновления 2023.06

**Comment by AlexxIT** [comment]
#19
