### ISSUE TITLE
HA 0.115+

### ISSUE THREAD

**Issue by InsaneGriever** [AlexxIT/MorphNumbers#5]
После обновления HA до 0.115 компонент перестал работать, ошибок в логах нет. 
пример: {{ 0|format(morph='градус') }}
вывод: 0

**Comment by AlexxIT** [comment]
Он долго скачивает зависимости. Должны быть ошибки в логах. У некоторых с третьей перезагрузки ставится. Нужно подождать.

**Comment by InsaneGriever** [comment]
При попытке перезагрузить HA.

```
Logger: aiohttp.server
Source: custom_components/morph_numbers/utils.py:14 
First occurred: 14:00:09 (1 occurrences) 
Last logged: 14:00:09

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 866, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 121, in async_check_ha_config_file
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 393, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/morph_numbers/__init__.py", line 4, in <module>
    from . import utils
  File "/config/custom_components/morph_numbers/utils.py", line 14, in <module>
    MORPH = MorphAnalyzer()
  File "/usr/local/lib/python3.8/site-packages/pymorphy2/analyzer.py", line 185, in __init__
    path = self.choose_dictionary_path(path, lang)
  File "/usr/local/lib/python3.8/site-packages/pymorphy2/analyzer.py", line 265, in choose_dictionary_path
    return lang_dict_path(lang)
  File "/usr/local/lib/python3.8/site-packages/pymorphy2/analyzer.py", line 126, in lang_dict_path
    raise ValueError(
ValueError: Can't find a dictionary for language 'ru'. Installed languages: []. Try installing pymorphy2-dicts-ru package.
```

**Comment by InsaneGriever** [comment]
После рестарта контейнера компонент заработал. Спасибо.

**Comment by alexanderznamensky** [comment]
Добрый день.

А какой контейнер надо рестартовать? Я уж и перегружал и переустанавливал несколько раз....
У меня сутки компонент не работает (НА 0.115.5 на Raspbian GNU/Linux 10 (buster)).
Также проверено на НА 0.115.5 на HassOS 4.13.
При этом на старой версии (НА 0.112.4) все взлетает мгновенно.

**Comment by InsaneGriever** [comment]
Через GUI HA не рестартился, копились ошибки на данный компонент в логах. После рестарта контейнера HA через портейнер, все завелось без проблем.

**Comment by alexanderznamensky** [comment]
спасибо! а у меня даже ошибок-то нет.... все рестартится..... и через GUI и через контейнер.
а вот на 0.112.4 все работает.....
странно.

**Comment by InsaneGriever** [comment]
Заметил на 0.115.3, сейчас 0.115.5. Проблем нет. (x86/Ubuntu Server 20.04 LTS/HA Supervised)

**Comment by alexanderznamensky** [comment]
спасибо. буду разбираться. я уже до 0.115.6 обновился. но пока результата нет )))

**Comment by InsaneGriever** [comment]
Сейчас посмотрел в шаблонах, проблема имеется.
Пример: {{states.sensor.cee22_temperature.state|round|format(morph='градус')}}
Вывод: двадцать три градуса

Пример: {{ 2|format(morph='просроченная задача') }}
Вывод: 2

Те работает только с указанием объекта.

**Comment by alexanderznamensky** [comment]
верно, у меня тоже так работает:
{{ states("sensor.0x00158d0004889a20_temperature") | round (1) | format(morph='градус') }}

**Comment by AlexKash500** [comment]
на HA 2021.1.3 тоже не работает

**Comment by AlexxIT** [comment]
Может просто не успел поставиться? На малинах или с плохим интернетом компонент может долго ставится после обновления версии ХА. После того как поставится - нужно перезагрузить ХА.

**Comment by alexanderznamensky** [comment]
Могу подтвердить - все работает.
Raspberry (Raspbian GNU/Linux 10 (buster)), Home Assistant 2021.1.3.
В шаблонах: {{ states("sensor.582d3436302c_temperature") | round (1) | format(morph='градус') }}
Вывод: двадцать три градуса.

**Comment by InsaneGriever** [comment]
Аналогично.
HA 2021.1.3 работает с указанием объекта и без. (x86/Ubuntu Server 20.04 LTS/HA Supervised)
